"""Create and check platform secrets.

`init` writes one random value per file under secrets/ (gitignored) and an
.env.observability file for Langfuse, which reads its settings from the
environment. Existing files are never overwritten unless asked to.
`check` scans the repository for anything that looks like a committed secret:
in a Git work tree it scans exactly the files Git would commit.
"""

from __future__ import annotations

import os
import re
import secrets as _random
import subprocess
from dataclasses import dataclass
from pathlib import Path

# File names map to environment variable names by upper-casing them,
# e.g. litellm_master_key -> LITELLM_MASTER_KEY (see platform/env-from-secrets.sh).
SECRET_SPECS: dict[str, str] = {
    "litellm_master_key": "sk-",
    "postgres_password": "",
    "langfuse_nextauth_secret": "",
    "langfuse_salt": "",
    "langfuse_public_key": "pk-lf-",
    "langfuse_secret_key": "sk-lf-",
    "langfuse_admin_password": "",
}

ENV_OBSERVABILITY = ".env.observability"

PATTERNS = {
    "openai-style key": re.compile(r"\bsk-[A-Za-z0-9_-]{20,}"),
    "langfuse public key": re.compile(r"\bpk-lf-[A-Za-z0-9_-]{16,}"),
    "private key block": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "aws access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "google api key": re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),
}

SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "secrets",
    "reports",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "node_modules",
    "build",
    "dist",
}
SKIP_FILES = {ENV_OBSERVABILITY, ".env"}


def _write_private(path: Path, value: str) -> None:
    path.write_text(value + "\n", encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:  # Windows: permissions are managed differently
        pass


def init_secrets(root: str | Path = ".", force: bool = False) -> list[str]:
    """Create missing secret files. Returns the names that were created."""
    root = Path(root)
    directory = root / "secrets"
    directory.mkdir(parents=True, exist_ok=True)
    created = []
    for name, prefix in SECRET_SPECS.items():
        path = directory / f"{name}.txt"
        if path.exists() and not force:
            continue
        _write_private(path, prefix + _random.token_urlsafe(32))
        created.append(name)
    write_env_observability(root)
    return created


def load_secrets(root: str | Path = ".") -> dict[str, str]:
    directory = Path(root) / "secrets"
    return {
        name: (directory / f"{name}.txt").read_text(encoding="utf-8").strip()
        for name in SECRET_SPECS
        if (directory / f"{name}.txt").exists()
    }


def write_env_observability(root: str | Path = ".") -> Path:
    values = load_secrets(root)
    lines = [
        "# Generated by `aiplat secrets init`. Gitignored. Do not commit.",
        f"DATABASE_URL=postgresql://langfuse:{values['postgres_password']}@postgres:5432/langfuse",
        f"NEXTAUTH_SECRET={values['langfuse_nextauth_secret']}",
        f"SALT={values['langfuse_salt']}",
        f"LANGFUSE_INIT_PROJECT_PUBLIC_KEY={values['langfuse_public_key']}",
        f"LANGFUSE_INIT_PROJECT_SECRET_KEY={values['langfuse_secret_key']}",
        f"LANGFUSE_INIT_USER_PASSWORD={values['langfuse_admin_password']}",
    ]
    path = Path(root) / ENV_OBSERVABILITY
    _write_private(path, "\n".join(lines))
    return path


@dataclass(frozen=True)
class Finding:
    path: str
    line: int
    kind: str


def _git_files(root: Path) -> list[Path] | None:
    """Files Git would commit (tracked, plus untracked files that are not ignored).
    Returns None when `root` is not inside a Git work tree."""
    try:
        result = subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "ls-files",
                "-z",
                "--cached",
                "--others",
                "--exclude-standard",
            ],
            capture_output=True,
            check=False,
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    names = [n for n in result.stdout.decode("utf-8", "replace").split("\0") if n]
    return [root / n for n in names if Path(n).name not in SKIP_FILES]


def _walk_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d
            for d in dirnames
            if d not in SKIP_DIRS and not (Path(dirpath, d) / "pyvenv.cfg").exists()
        ]
        for filename in filenames:
            if filename not in SKIP_FILES:
                yield Path(dirpath) / filename


def _iter_files(root: Path):
    files = _git_files(root)
    if files is None:
        yield from _walk_files(root)
        return
    # No directory skipping here: a secret file someone force-added must be found.
    yield from (path for path in files if path.is_file())


def scan_for_secrets(root: str | Path = ".") -> list[Finding]:
    """Find committed-looking secrets, including the exact values in secrets/."""
    root = Path(root)
    known = {v for v in load_secrets(root).values() if len(v) >= 12}
    findings = []
    for path in _iter_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for line_no, line in enumerate(text.splitlines(), 1):
            for kind, pattern in PATTERNS.items():
                if pattern.search(line):
                    findings.append(Finding(str(path.relative_to(root)), line_no, kind))
            if any(value in line for value in known):
                findings.append(
                    Finding(str(path.relative_to(root)), line_no, "value from secrets/")
                )
    return findings
